# ==============================================================================
# CAZIL SYSTEM - CONFIGURACIÓN DE HYPRPAPER (WALLPAPERS)
# ==============================================================================

# Precargar wallpaper en memoria
preload = /home/p4x/Proyectos/VisualS/cazil-dotfiles/themes/218/wallpapers/unnamed_clean.jpg

# Aplicar wallpaper a todos los monitores (coma = todos los monitores)
wallpaper = ,/home/p4x/Proyectos/VisualS/cazil-dotfiles/themes/218/wallpapers/unnamed_clean.jpg

# Desactivar splash screen
splash = false

# Desactivar IPC (interfaz de comunicación entre procesos)
ipc = off
