# ==============================================================================
# CAZIL SYSTEM - CONFIGURACIÓN DE HYPRPAPER (WALLPAPERS)
# ==============================================================================

# Precargar wallpaper en memoria
preload = ~/Pictures/wallpapers/bg_grub1_con_logo.png

# Aplicar wallpaper a todos los monitores (coma = todos los monitores)
wallpaper = ,~/Pictures/wallpapers/bg_grub1_con_logo.png

# Desactivar splash screen
splash = false

# Desactivar IPC (interfaz de comunicación entre procesos)
ipc = off
