# ==============================================================================
# CAZIL - MONITOR CONFIG: INTERNO ÚNICO (Modo Unificado)
# Archivo: ~/cazil-dots/hypr/monitores_internos.conf
# ==============================================================================

# Solo la Laptop activa (60Hz default para ahorro de batería)
monitor = eDP-1, 1920x1080@60, 0x0, 1

# Workspaces en monitor interno
workspace = 2, monitor:eDP-1, default:true    # W2: Trabajo (por defecto)
workspace = 10, monitor:eDP-1                 # W10: Notas privadas